{{- $fullName := include "web-static.fullname" . -}}
{{- range .Values.ingress.tls }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .secretName }}
  namespace: {{ $.Values.certificate.namespace | default $.Release.namespace  | quote }}
spec:
  secretName: {{ .secretName }}
  dnsNames:
  {{- range .hosts }}
    - {{ . | quote }}
  {{- end }}
  issuerRef:
    name: {{ $.Values.certificate.issuerRef.name }}
    kind: {{ $.Values.certificate.issuerRef.kind }}
{{- end }}
