acme:
  email: ""
  server: "https://acme-v02.api.letsencrypt.org/directory"
secret: 
  enabled: true
  namespace: default
  name: cloudflare-secret
  value: cloudflare-secret-you-know
solvers:
  htto01: {}
  dns01: 
    cloudflare:
      enabled: true
      email: your-email@you.know
ingress:
    class: istio
    serviceType: ClusterIP
    annotations: 
        "kubernetes.io/ingress.class": "istio"
