apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "acme-cluster-issuer.fullname" . }}
  labels:
    {{- include "acme-cluster-issuer.labels" . | nindent 4 }}
spec:
  acme:
    email: {{ .Values.acme.email }}
    server: {{ .Values.acme.server }}
    privateKeySecretRef:
      name: {{ include "acme-cluster-issuer.fullname" . }}-account-key
    solvers:
    {{- if .Values.solvers.http01 }}
      - http01:
          ingress:
            class: {{ .Values.ingress.class }}
            serviceType: {{ .Values.ingress.serviceType }}
            ingressTemplate:
              metadata:
                annotations:
                  {{- range $key, $value := .Values.ingress.annotations }}
                  {{ $key }}: {{ $value | quote }}
                  {{- end }}
    {{- end }}
    {{- if .Values.solvers.dns01}}
      - dns01:
        {{- if .Values.solvers.dns01.cloudflare.enabled }}
        {{ with  .Values.solvers.dns01.cloudflare }}
          cloudflare: 
            email: {{ .email }}
            apiTokenSecretRef:
              name: {{ $.Values.secret.name }}
              key: value
        {{- end }}
        {{- end }}
    {{- end }}
