apiVersion: v1
kind: Service
metadata:
  name: {{ include "pomoday.fullname" . }}-backend
  labels:
    {{- include "pomoday.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pomoday.selectorLabels" . | nindent 4 }}
    # TODO: Move it to templates
    app.kubernetes.io/name: pomoday-backend
